GO
USE DB_QUINIELAS
GO

IF EXISTS (SELECT * FROM sys.objects WHERE TYPE = 'p' AND name = 'SP_REGISTRO')
DROP PROCEDURE SP_REGISTRO
GO
IF EXISTS (SELECT * FROM sys.objects WHERE TYPE = 'p' AND name = 'SP_CREDENCIALES')
DROP PROCEDURE SP_CREDENCIALES
GO
IF EXISTS (SELECT * FROM sys.objects WHERE TYPE = 'p' AND name = 'SP_ACTUALIZACION_RESULTADOS')
DROP PROCEDURE SP_ACTUALIZACION_RESULTADOS
GO


/*CREACION DE CUENTAS*/
CREATE PROC SP_REGISTRO(
@NOMBRES VARCHAR (50),
@APELLIDOS VARCHAR (50),
@TELEFONO INTEGER,
@EMAIL VARCHAR (30),
@PASSWORD VARCHAR (30)
)AS
DECLARE @CONTADOR INT
--VERIFICA SI EL EMAIL YA SE ENCUENTRA REGISTRADO
SELECT @CONTADOR = COUNT(U.ID_USUARIO) FROM USUARIO U WHERE U.CORREO = @EMAIL

IF(@CONTADOR < 1)
	BEGIN
		INSERT INTO USUARIO(NOMBRES,APELLIDOS,TELEFONO,CORREO,CONTRASEÑA)
		VALUES(@NOMBRES,@APELLIDOS,@TELEFONO,@EMAIL,@PASSWORD)
	END
ELSE
	BEGIN
		SELECT 'El correo ingresado se encuentra repetido, por favor inténtelo nuevamente.' AS MENSAJE_ERROR
	END



GO


/*INICIO DE SESIÓN EN EL SISTEMA*/
CREATE PROC SP_CREDENCIALES(
@EMAIL VARCHAR (30),
@PASSWORD VARCHAR (30)
)AS
BEGIN
SELECT U.ID_USUARIO, U.NOMBRES, U.APELLIDOS, U.TELEFONO, U.CORREO
FROM USUARIO U
WHERE U.CORREO = @EMAIL AND U.CONTRASEÑA = @PASSWORD
END
GO



/*INGRESO POR PARTE DE LA ADMINISTRACION LOS RESULTADOS FINALES DE CADA ENCUENTRO (GOLES DE LOCAL Y GOLES DE VISITANTE) Y ENTREGA DE PUNTOS A CADA APUESTA DE LOS USUARIOS*/
CREATE PROC SP_ACTUALIZACION_RESULTADOS(
@ID_JORNADA VARCHAR (10),
@ID_EQUIPOLOCAL VARCHAR (10),
@ID_EQUIPOVISITANTE VARCHAR(10),
@GOLES_LOCAL INTEGER,
@GOLES_VISITANTE INTEGER
)AS
DECLARE @CONTADOR INT
--VERIFICA SI EN LA JORNADA INGRESADA POR EL USUARIO SE ENFRENTARON EL EQUIPO LOCAL Y EL EQUIPO VISITANTE
SELECT @CONTADOR = COUNT(ID_JORNADA) FROM PARTIDOS P WHERE P.ID_JORNADA = @ID_JORNADA AND P.ID_EQUIPOLOCAL = @ID_EQUIPOLOCAL AND P.ID_EQUIPOVISITANTE = @ID_EQUIPOVISITANTE

IF(@CONTADOR > 0)
	BEGIN
		--ACTUALIACIÓN DEL RESULTADO DE LOS PARTIDOS EN LA TABLA PARTIDOS
		UPDATE PARTIDOS SET
		GOLES_LOCAL = @GOLES_LOCAL,
		GOLES_VISITANTE = @GOLES_VISITANTE
		WHERE ID_JORNADA = @ID_JORNADA AND ID_EQUIPOLOCAL = @ID_EQUIPOLOCAL AND ID_EQUIPOVISITANTE = @ID_EQUIPOVISITANTE

		--ASIGNACIÓN DE PUNTOS A LOS USUARIOS DE ACUERDO AL RESULTADO DEL PARTIDO INGRESADO
		IF(@GOLES_LOCAL>@GOLES_VISITANTE)
			BEGIN
				UPDATE APUESTA SET
				PUNTOS_OBTENIDOS = 1
				WHERE ID_JORNADA = @ID_JORNADA AND ID_EQUIPOLOCAL = @ID_EQUIPOLOCAL AND ID_EQUIPOVISITANTE = @ID_EQUIPOVISITANTE AND APUESTA_LOCAL > APUESTA_VISITANTE

				UPDATE APUESTA SET
				PUNTOS_OBTENIDOS = 3
				WHERE ID_JORNADA = @ID_JORNADA AND ID_EQUIPOLOCAL = @ID_EQUIPOLOCAL AND ID_EQUIPOVISITANTE = @ID_EQUIPOVISITANTE AND APUESTA_LOCAL = @GOLES_LOCAL AND APUESTA_VISITANTE = @GOLES_VISITANTE
			END
		ELSE IF(@GOLES_LOCAL<@GOLES_VISITANTE)
			BEGIN
				UPDATE APUESTA SET
				PUNTOS_OBTENIDOS = 1
				WHERE ID_JORNADA = @ID_JORNADA AND ID_EQUIPOLOCAL = @ID_EQUIPOLOCAL AND ID_EQUIPOVISITANTE = @ID_EQUIPOVISITANTE AND APUESTA_LOCAL < APUESTA_VISITANTE

				UPDATE APUESTA SET
				PUNTOS_OBTENIDOS = 3
				WHERE ID_JORNADA = @ID_JORNADA AND ID_EQUIPOLOCAL = @ID_EQUIPOLOCAL AND ID_EQUIPOVISITANTE = @ID_EQUIPOVISITANTE AND APUESTA_LOCAL = @GOLES_LOCAL AND APUESTA_VISITANTE = @GOLES_VISITANTE
			END
		ELSE
			BEGIN
				UPDATE APUESTA SET
				PUNTOS_OBTENIDOS = 1
				WHERE ID_JORNADA = @ID_JORNADA AND ID_EQUIPOLOCAL = @ID_EQUIPOLOCAL AND ID_EQUIPOVISITANTE = @ID_EQUIPOVISITANTE AND APUESTA_LOCAL = APUESTA_VISITANTE

				UPDATE APUESTA SET
				PUNTOS_OBTENIDOS = 3
				WHERE ID_JORNADA = @ID_JORNADA AND ID_EQUIPOLOCAL = @ID_EQUIPOLOCAL AND ID_EQUIPOVISITANTE = @ID_EQUIPOVISITANTE AND APUESTA_LOCAL = @GOLES_LOCAL AND APUESTA_VISITANTE = @GOLES_VISITANTE
			END

	END
ELSE
	BEGIN
		SELECT 'El partido no existe, por favor inténtalo nuevamente.' AS MENSAJE_ERROR
	END
GO
















